#!/bin/bash

ENCFILE=$1
OUTDIR="${PWD}/"

# Check for required binaries
if ! [[ -x "$(command -v openssl)" && -x "$(command -v tar)" ]]; then
	echo "Please ensure that openssl and tar are installed."
	exit 1
fi

# Decrypt file downloaded from Google Drive
dec() {
	openssl enc -aes-256-cbc -d -in $ENCFILE | tar -xz
	echo "Now copy the extracted bin to ${PWD}, and run ./decompile to dump partitions."
}

dec
